packages:
  - '.'
minimumReleaseAgeExclude:
  - mastra
  - "@mastra/*"
allowBuilds:
  '@scarf/scarf': false
  bufferutil: true
  esbuild: true
  msedge-tts: false
  protobufjs: true
  sharp: true
  utf-8-validate: true
